name: Continuous Delivery

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types:
      - trigger-build

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Generate stackbrew library
      run: |
        git clone --depth 1 https://github.com/docker-library/bashbrew.git -b master ~/bashbrew
        (
          cd ~/bashbrew
          GO111MODULE=on go build -o bin/bashbrew ./cmd/bashbrew
        )
        export PATH="$HOME/bashbrew/bin:$PATH"
        mkdir ~/library
        ./generate-stackbrew-library.sh > ~/library/postgresql
    - name: Build image
      env:
        BASHBREW_NAMESPACE: quay.io/enterprisedb/
      run: |
        export PATH="$HOME/bashbrew/bin:$PATH"
        bashbrew --library "$HOME/library" build postgresql
    - name: Dockle Scan
      if: success()
      run: |
        echo "docker images availables:" && docker images
        DOCKLEVERSION=$(
          curl --silent "https://api.github.com/repos/goodwithtech/dockle/releases/latest" | \
          grep '"tag_name":' | \
          sed -E 's/.*"v([^"]+)".*/\1/' \
        ) && curl -L -o dockle.tar.gz https://github.com/goodwithtech/dockle/releases/download/v${DOCKLEVERSION}/dockle_${DOCKLEVERSION}_Linux-64bit.tar.gz
        tar zxvf dockle.tar.gz
        imagestoscan=( "$@" )
        if [ ${#imagestoscan[@]} -eq 0 ]; then
                imagestoscan=( $(ls -d */ | grep -v ^src/) )
        fi
        imagestoscan=( "${imagestoscan[@]%/}" )
        for imagetoscan in "${imagestoscan[@]}"; do
          echo "scanning postgresql:${imagetoscan} image..."
          ./dockle --exit-code 1 --exit-level warn bashbrew/cache:$(docker images | grep "$(docker images | grep ' ${imagetoscan} ' | awk '{print $3}')" | grep 'bashbrew/cache' | awk '{print $2}')
        done
    - name: Docker Login
      if: success()
      env:
        QUAY_USER: ${{ secrets.QUAY_USER }}
        QUAY_KEY: ${{ secrets.QUAY_KEY }}
        QUAY_REPO: ${{ secrets.QUAY_REPO }}
      run: |
        echo "${QUAY_KEY}" | docker login --username "${QUAY_USER}" --password-stdin "${QUAY_REPO}"
    - name: Push image
      if: success()
      env:
        BASHBREW_NAMESPACE: quay.io/enterprisedb/
      run: |
        export PATH="$HOME/bashbrew/bin:$PATH"
        bashbrew --library "$HOME/library" push postgresql
    - name: Clear
      if: always()
      run: |
        rm -f "${HOME}/.docker/config.json"
