name: Continuous Delivery

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types:
      - trigger-build

env:
  IMAGE_STAGING: quay.io/enterprisedb/postgresql-testing
  IMAGE_RELEASE: quay.io/enterprisedb/postgresql

jobs:
  generate-jobs:
    name: Generate Jobs
    runs-on: ubuntu-20.04
    outputs:
      strategy: ${{ steps.generate-jobs.outputs.strategy }}
    steps:
      - uses: actions/checkout@v2
      - id: generate-jobs
        name: Generate Jobs
        run: .github/generate-strategy.sh

  build:
    needs: generate-jobs
    strategy: ${{ fromJson(needs.generate-jobs.outputs.strategy) }}
    name: ${{ matrix.version }}
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Docker meta
      id: docker-meta
      env:
        TAGS: ${{ toJson(matrix.tags) }}
      run: |
        RESULT=""
        for tag in $(jq -r '.[]' <<< "${TAGS}")
        do
          RESULT="${RESULT},${IMAGE_STAGING}:${tag}"
          # If we are running the pipeline in the main branch images are pushed in both -testing and PROD repo
          if [ "${GITHUB_REF#refs/heads/}" == main ]
          then
            RESULT="${RESULT},${IMAGE_RELEASE}:${tag}"
          fi
        done
        echo "::set-output name=tags::${RESULT%,}"
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to quay.io
      uses: docker/login-action@v1
      with:
        registry: quay.io/enterprisedb
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ${{ matrix.version }}
        # Available architecture on UBI8 are: linux/amd64, linux/arm64, linux/ppc64le
        platforms: linux/amd64
        push: true
        tags: ${{ steps.docker-meta.outputs.tags }}
        labels: ${{ github.ref != 'refs/heads/main' && 'quay.expires-after=7d' || '' }}
    - name: Dockle scan
      uses: hands-lab/dockle-action@v1
      with:
        image: "${{ env.IMAGE_STAGING }}:${{ matrix.tags[0] }}"
        exit-code: '1'
        exit-level: WARN
      env:
        DOCKLE_USERNAME: ${{ secrets.QUAY_USERNAME }}
        DOCKLE_PASSWORD: ${{ secrets.QUAY_TOKEN }}
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      if: ${{ failure() }}
      env:
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://avatars.githubusercontent.com/u/44036562?size=48
        SLACK_USERNAME: ghBot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  # Send a notification if new public images are released
  notify:
    needs: build
    name: Notify update on Slack
    runs-on: ubuntu-20.04
    steps:
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      # Only images built from the main branch go public, and we limit the
      # amount of notifications to those.
      if: ${{ github.ref == 'refs/heads/main' }}
      env:
        SLACK_ICON: https://avatars.githubusercontent.com/u/44036562?size=48
        SLACK_USERNAME: ghBot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: New PostgreSQL images pushed on Quay.io
