name: Continuous Delivery

on:
  push:
    branches:
      - main
  repository_dispatch:
    types:
      - trigger-build

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Generate stackbrew library
      run: |
        git clone --depth 1 https://github.com/docker-library/bashbrew.git -b master ~/bashbrew
        (
          cd ~/bashbrew
          GO111MODULE=on go build -o bin/bashbrew ./cmd/bashbrew
        )
        export PATH="$HOME/bashbrew/bin:$PATH"
        mkdir ~/library
        ./generate-stackbrew-library.sh > ~/library/postgresql
    - name: Build image
      env:
        BASHBREW_NAMESPACE: quay.io/enterprisedb/
      run: |
        export PATH="$HOME/bashbrew/bin:$PATH"
        bashbrew --library "$HOME/library" build postgresql
    - uses: hands-lab/dockle-action@v1
      name: Dockle scan
      if: success()
      with:
        image: postgresql
    - name: Docker Login
      if: success()
      env:
        QUAY_USER: ${{ secrets.QUAY_USER }}
        QUAY_KEY: ${{ secrets.QUAY_KEY }}
        QUAY_REPO: ${{ secrets.QUAY_REPO }}
      run: |
        echo "${QUAY_KEY}" | docker login --username "${QUAY_USER}" --password-stdin "${QUAY_REPO}"
    - name: Push image
      if: success()
      env:
        BASHBREW_NAMESPACE: quay.io/enterprisedb/
      run: |
        export PATH="$HOME/bashbrew/bin:$PATH"
        bashbrew --library "$HOME/library" push postgresql
    - name: Clear
      if: always()
      run: |
        rm -f "${HOME}/.docker/config.json"
