name: Automatic Updates

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
      - name: Run update script
        uses: nick-invision/retry@v2.4.1
        with:
          timeout_minutes: 15
          max_attempts: 3
          command: |
            # pip-tools provides pip-compile used by update.sh
            export PATH=$HOME/.local/bin:$PATH
            pip3 install pip-tools
            echo "Updating UBI images"
            ./UBI/update.sh
            echo "Updating Debian Images"
            ./Debian/update.sh
      - name: Diff
        run: |
          git status
          git diff
      - uses: EndBug/add-and-commit@v7
        id: commit
        with:
          author_name: EnterpriseDB Automated Updates
          author_email: noreply@enterprisedb.com
          message: 'Daily automatic update'
