name: Automatic Updates

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # pip-tools provides pip-compile used by update.sh on the next step
          pip install pip-tools
      - name: Run update script
        uses: nick-invision/retry@v2.4.0
        with:
          timeout_minutes: 15
          max_attempts: 3
          command: ./update.sh
      - name: Diff
        run: |
          git status
          git diff
      - uses: EndBug/add-and-commit@v7
        id: commit
        with:
          author_name: EnterpriseDB Automated Updates
          author_email: noreply@enterprisedb.com
          message: 'Daily automatic update'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Dispatch trigger-e2e event
        if: steps.commit.outputs.committed == 'true'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          repository: ${{ github.repository }}
          event-type: trigger-build
