name: Automatic Updates

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
      - name: Update docker-entrypoint
        uses: nick-fields/retry@v2.7.1
        with:
          timeout_seconds: 20
          max_attempts: 3
          command: |
            echo "Updating Debian docker-entrypoint"
            curl -fsSo ./Debian/src/root/usr/local/bin/docker-entrypoint.sh https://raw.githubusercontent.com/docker-library/postgres/master/docker-entrypoint.sh
            echo "Updating UBI docker-entrypoint"
            cp ./Debian/src/root/usr/local/bin/docker-entrypoint.sh ./UBI/src/root/usr/local/bin/docker-entrypoint.sh
            cp ./Debian/src/root/usr/local/bin/docker-entrypoint.sh ./IronBank/src/root/scripts/docker-entrypoint.sh
      - name: Run update script
        uses: nick-fields/retry@v2.7.1
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
          BASE_REGISTRY: "registry.access.redhat.com"
          BASE_IMAGE: "ubi8"
        with:
          timeout_minutes: 15
          max_attempts: 3
          command: |
            # pip-tools provides pip-compile used by update.sh
            export PATH=$HOME/.local/bin:$PATH
            # TODO: Remove pip workaround once https://github.com/jazzband/pip-tools/issues/1558 is fixed
            pip3 install --upgrade pip-tools cloudsmith-cli 'pip<22'
            echo "Updating UBI images"
            ./UBI/update.sh
            echo "Updating Debian images"
            ./Debian/update.sh
            echo "Updating IronBank images"
            ./IronBank/update.sh
      - name: Diff
        run: |
          git status
          git diff
      - name: Temporarily disable "include administrators" branch protection
        if: ${{ always() && github.ref == 'refs/heads/main' }}
        id: disable_include_admins
        uses: benjefferies/branch-protection-bot@1.0.7
        with:
          access_token: ${{ secrets.REPO_GHA_PAT }}
          branch: main
          enforce_admins: false
      - uses: EndBug/add-and-commit@v9
        id: commit
        with:
          author_name: EnterpriseDB Automated Updates
          author_email: noreply@enterprisedb.com
          message: 'Daily automatic update'
      - name: Enable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@1.0.7
        if: ${{ always() && github.ref == 'refs/heads/main' }}
        with:
          access_token: ${{ secrets.REPO_GHA_PAT }}
          branch: main
          enforce_admins: ${{ steps.disable_include_admins.outputs.initial_status }}
